#spring:
#  datasource:
#    username: root
#    password: Password1
#    url: jdbc:mysql://localhost:3306/shopit?allowPublicKeyRetrieval=true&useSSL=FALSE
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialectspring